Base:
    model_id: anomaly_transformer
    normalize: "minmax"

anomaly_transformer_SMD:
    dataset_id: SMD
    batch_size: 128
    window_size: 100
    nb_epoch: 10
    l2_regularizer: 0.1
    stride: 1
    num_workers: 1
    lr: 1.0e-4
    k: 3
    device: 2

anomaly_transformer_ASD:
    dataset_id: ASD
    batch_size: 128
    window_size: 100
    nb_epoch: 10
    l2_regularizer: 0.1
    stride: 1
    num_workers: 1
    lr: 1.0e-4
    k: 3
    device: 2

anomaly_transformer_SWAT:
    dataset_id: SWAT
    batch_size: 128
    window_size: 100
    nb_epoch: 10
    l2_regularizer: 0.1
    stride: 1
    num_workers: 1
    lr: 1.0e-4
    k: 3
    device: 2

anomaly_transformer_WADI:
    dataset_id: WADI
    batch_size: 128
    window_size: 100
    nb_epoch: 10
    l2_regularizer: 0.1
    stride: 1
    num_workers: 1
    lr: 1.0e-4
    k: 3
    device: 2

anomaly_transformer_SMAP:
    dataset_id: SMAP
    batch_size: 128
    window_size: 100
    nb_epoch: 10
    l2_regularizer: 0.1
    stride: 1
    num_workers: 1
    lr: 1.0e-4
    k: 3
    device: 2

anomaly_transformer_MSL:
    dataset_id: MSL
    batch_size: 128
    window_size: 100
    nb_epoch: 10
    l2_regularizer: 0.1
    stride: 1
    num_workers: 1
    lr: 1.0e-4
    k: 3
    device: 2

