Base:
    normalize: "standard"
    model_id: dagmm
    reverse_score: False

dagmm_SMD:
    dataset_id: SMD
    batch_size: 512
    nb_epoch: 20
    compression_hiddens: [128, 64, 2]
    estimation_hiddens: [100, 50]
    estimation_dropout_ratio: 0.25
    lr: 0.0001
    lambdaone: 0.1
    lambdatwo: 0.0001
    device: 2
dagmm_ASD:
    dataset_id: ASD
    batch_size: 512
    nb_epoch: 20
    compression_hiddens: [128, 64, 2]
    estimation_hiddens: [100, 50]
    estimation_dropout_ratio: 0.25
    lr: 0.0001
    lambdaone: 0.1
    lambdatwo: 0.0001
    device: 2
dagmm_SWAT:
    dataset_id: SWAT
    batch_size: 512
    nb_epoch: 20
    compression_hiddens: [128, 64, 2]
    estimation_hiddens: [100, 50]
    estimation_dropout_ratio: 0.25
    lr: 0.0001
    lambdaone: 0.1
    lambdatwo: 0.0001
    device: 2
dagmm_WADI:
    dataset_id: WADI
    batch_size: 512
    nb_epoch: 20
    compression_hiddens: [128, 64, 2]
    estimation_hiddens: [100, 50]
    estimation_dropout_ratio: 0.25
    lr: 0.0001
    lambdaone: 0.1
    lambdatwo: 0.0001
    device: 2
dagmm_SMAP:
    dataset_id: SMAP_test
    batch_size: 512
    nb_epoch: 20
    compression_hiddens: [128, 64, 2]
    estimation_hiddens: [100, 5]
    estimation_dropout_ratio: 0
    lr: 0.001
    lambdaone: 0
    lambdatwo: 0
    device: 2
dagmm_MSL:
    dataset_id: MSL
    batch_size: 512
    nb_epoch: 20
    compression_hiddens: [128, 64, 2]
    estimation_hiddens: [100, 50]
    estimation_dropout_ratio: 0.25
    lr: 0.0001
    lambdaone: 0.1
    lambdatwo: 0.0001
    device: 2

