Base:
    model_id: mtad_gat
    normalize: "minmax"

mtad_gat_SMD:
    dataset_id: SMD
    batch_size: 512
    window_size: 100
    stride: 1
    nb_epoch: 10
    shuffle: True
    num_workers: 1
    init_lr: 3.0e-4
    kernel_size: 7
    feat_gat_embed_dim: null
    time_gat_embed_dim: null
    use_gatv2: True
    gru_n_layers: 1
    gru_hid_dim: 150
    forecast_n_layers: 1
    forecast_hid_dim: 150
    recon_n_layers: 1
    recon_hid_dim: 150
    dropout: 0.3
    alpha: 0.2
    gamma: 1
    device: 3
mtad_gat_ASD:
    dataset_id: ASD
    batch_size: 512
    window_size: 100
    stride: 1
    nb_epoch: 10
    shuffle: True
    num_workers: 1
    init_lr: 3.0e-4
    kernel_size: 7
    feat_gat_embed_dim: null
    time_gat_embed_dim: null
    use_gatv2: True
    gru_n_layers: 1
    gru_hid_dim: 150
    forecast_n_layers: 1
    forecast_hid_dim: 150
    recon_n_layers: 1
    recon_hid_dim: 150
    dropout: 0.3
    alpha: 0.2
    gamma: 1
    device: 3
mtad_gat_SWAT:
    dataset_id: SWAT
    batch_size: 512
    window_size: 100
    stride: 1
    nb_epoch: 10
    shuffle: True
    num_workers: 1
    init_lr: 3.0e-4
    kernel_size: 7
    feat_gat_embed_dim: null
    time_gat_embed_dim: null
    use_gatv2: True
    gru_n_layers: 1
    gru_hid_dim: 150
    forecast_n_layers: 1
    forecast_hid_dim: 150
    recon_n_layers: 1
    recon_hid_dim: 150
    dropout: 0.3
    alpha: 0.2
    gamma: 1
    device: 3
mtad_gat_WADI:
    dataset_id: WADI
    batch_size: 128
    window_size: 100
    stride: 1
    nb_epoch: 10
    shuffle: True
    num_workers: 1
    init_lr: 3.0e-4
    kernel_size: 7
    feat_gat_embed_dim: null
    time_gat_embed_dim: null
    use_gatv2: True
    gru_n_layers: 1
    gru_hid_dim: 150
    forecast_n_layers: 1
    forecast_hid_dim: 150
    recon_n_layers: 1
    recon_hid_dim: 150
    dropout: 0.3
    alpha: 0.2
    gamma: 1
    device: 3
mtad_gat_SMAP:
    dataset_id: SMAP
    batch_size: 512
    window_size: 100
    stride: 1
    nb_epoch: 10
    shuffle: True
    num_workers: 1
    init_lr: 3.0e-4
    kernel_size: 7
    feat_gat_embed_dim: null
    time_gat_embed_dim: null
    use_gatv2: True
    gru_n_layers: 1
    gru_hid_dim: 150
    forecast_n_layers: 1
    forecast_hid_dim: 150
    recon_n_layers: 1
    recon_hid_dim: 150
    dropout: 0.3
    alpha: 0.2
    gamma: 1
    device: 3
mtad_gat_MSL:
    dataset_id: MSL
    batch_size: 256
    window_size: 100
    stride: 1
    nb_epoch: 10
    shuffle: True
    num_workers: 1
    init_lr: 3.0e-4
    kernel_size: 7
    feat_gat_embed_dim: null
    time_gat_embed_dim: null
    use_gatv2: True
    gru_n_layers: 1
    gru_hid_dim: 150
    forecast_n_layers: 1
    forecast_hid_dim: 150
    recon_n_layers: 1
    recon_hid_dim: 150
    dropout: 0.3
    alpha: 0.2
    gamma: 1
    device: 1
